### ISSUE TITLE
Depreciation error

### ISSUE THREAD

**Issue by jeffgroversr** [mortada/fredapi#18]
When using this command: 
data = fred.get_series_first_release('GDP') 
data.tail()

I get this error: C:\Users\Valued Customer\Anaconda3\lib\site-packages\fredapi\fred.py:242: FutureWarning: to_datetime is deprecated. Use self.to_pydatetime() realtime_start = self._parse(child.get('realtime_start')) 
C:\Users\Valued Customer\Anaconda3\lib\site-packages\fredapi\fred.py:244: FutureWarning: to_datetime is deprecated. Use self.to_pydatetime() date = self._parse(child.get('date'))

Does your code need to be updated?

**Comment by mortada** [comment]
thanks for reporting - I pushed a commit that should remove this warning

https://github.com/mortada/fredapi/commit/b0e1b2b5334219749b9e17035ab1b80fc261c256

**Comment by mortada** [comment]
should be fixed in version `0.4.0`, I just published on pypi, thanks!
