### ISSUE TITLE
Vintage Dates Limit

### ISSUE THREAD

**Issue by abadrinath15** [mortada/fredapi#28]
Hello @mortada; thanks for a really great library! I noticed an interesting issue -- I think FRED has a limitation on vintage dates for a query (I believe it's 2000). I ran into this when trying to call `get_series_all_releases` with `series_id='DFF'` (Effective Fed Funds Rate, published daily). As is, there wasn't a good way to get around it since the `realtime_start` and `realtime_end` parameters are class variables instead of being passed in. I believe the code just errors out (i.e. it doesn't even provide a partial data set) . 

Here is my proposal for a solution; see if it makes sense: 

1. Allow `realtime_start` and `realtime_end` to be arguments (defaulted to None so it doesn't break anyone's code)
2. If the arguments are not None, update `self.realtime_start` and `self.realtime_end` to new values
3. Run `get_series_vintage_dates` on the `series_id` and see if there are more than 2,000 values within the `self.realtime_start` and `self.realtime_end` values
4. If not, return the dataset with new values. 
5. If > 2,000... I am not 100% certain what the best way to handle it would be. I'm biased towards taking the most recent 2,000 values, but perhaps that wouldn't be the best/ most consistent behavior? 

If you agree with the idea, I'm happy to code it up and submit a pull request! Thank you.

**Comment by SellmessengerCloud** [comment]
I'm getting the same error for the code M3 = fred.get_series_first_release('DTB3'), but I'm already using Version 0.5.

**Comment by SellmessengerCloud** [comment]
Also interesting: For fred.get_series_first_release('DTB1') the code works, even though there are 10322 data points (this means 10322 "vintage dates" right?) So apparently this Fred rate limit only applies to certain series. Does anyone know which ones?
