### ISSUE TITLE
Series does not exist Issue : Libor 1M + 3M + Overnight

### ISSUE THREAD

**Issue by datarocksAmy** [mortada/fredapi#34]
## Describe the Bug
Getting below error message when calling Libor rates series ids from fredapi.
It was working just fine last week. Start occurring error after 09/13/2020.

```
Traceback (most recent call last):
  File "C:\Users\amylin\Desktop\DevOp\FR\venv\lib\site-packages\fredapi\fred.py", line 64, in __fetch_data
    response = urlopen(url)
  File "C:\Users\amylin\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\amylin\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\amylin\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\amylin\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\amylin\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\amylin\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\amylin\Desktop\DevOp\ATG.FinanceRates\venv\lib\site-packages\fredapi\fred.py", line 131, in get_series
    root = self.__fetch_data(url)
  File "C:\Users\amylin\Desktop\DevOp\ATG.FinanceRates\venv\lib\site-packages\fredapi\fred.py", line 68, in __fetch_data
    raise ValueError(root.get('message'))
ValueError: Not Found.  The series does not exist.
```

- #### Command Name
fred_endpoint.get_series_all_releases(series_id)

## To Reproduce
Call `fred_endpoint.get_series_all_releases(series_id)` with the following series_id:
- USD1MTD156N ( One Month Libor )
- USD3MTD156N ( Three Month Libor )
- USDONTD156N ( Libor Overnight )
<br>

## Expected Behavior
Return historical rates from Fred

## Environment Summary
```
Windows-10-10.0.17134 Build 17134
Python 3.7.3
fredapi 0.4.2
```
## Additional Context

I have forked the master to dig into where the issue is coming from.
I directly did a request toward Fred API endpoint and it is still returning bad request.
From my observation/investigation, this is caused by Fred API instead of the package.
I've notified Federal Reserve Bank of St Louis about the issue.
<br>

**Comment by Lucianoris** [comment]
I am facing similar issues with US Libor rates. At some point Libor rates are going to be phased out I believe (talks speculate this will happen in Dec 2021) I just hope they did not discontinue the series without informing users.  Thanks for raising this with the FRED. I  have also raised this. Please let us know once you have a reply. Cheers

**Comment by datarocksAmy** [comment]
> I am facing similar issues with US Libor rates. At some point Libor rates are going to be phased out I believe (talks speculate this will happen in Dec 2021) I just hope they did not discontinue the series without informing users. Thanks for raising this with the FRED. I have also raised this. Please let us know once you have a reply. Cheers


From FRED. They would be discontinuing the following rate due to ICE regulation : **ICE Libor Rates, ICE Swap Rates, LBMA Gold Price**
See following for the email replied from FRED:
`The source of the following releases, ICE Libor Rates, ICE Swap Rates, LBMA Gold Price: Daily Prices, and LBMA Silver Price: Daily Prices, will not let us redistribute their data in our Excel Addin and API. Previously, this data was in the FRED products. The series will no longer be accessible through the above-mentioned products. `

**Comment by Lucianoris** [comment]
Agreed, Many thanks for chasing this up.

Cheers

**Comment by datarocksAmy** [comment]
Closed issue due to restricted redistribution of following rates. It would be great to add this note on the package documentation site / github page.
 **ICE Libor Rates, ICE Swap Rates, LBMA Gold Price:Daily Prices, and LBMA Silver Price: Daily Prices**

**Comment by actlienholding** [comment]
Any idea if any other API does provide this data?
