### ISSUE TITLE
fredapi doesn't work anymore with Python 3.9, uses removed function getchildren

### ISSUE THREAD

**Issue by mj-64** [mortada/fredapi#36]
Using Python 3.9, fredapi does not work any longer because it uses the function getchildren() for xml.etree.Elements. This function is deprecated and has been removed with Python 3.9.

I created a pull request to fix it:

Solution: Just remove all getchildren() calls and change to iteration, e.g in get_series():

```for child in root.getchildren(): ...```

change to: 

```for child in root: ...```

See https://docs.python.org/3.8/library/xml.etree.elementtree.html and https://docs.python.org/3.9/library/xml.etree.elementtree.html, search for getchildren()

**Comment by mortada** [comment]
@mj-64 thanks for reporting this! version 0.4.3 includes your fix and has been published
