### ISSUE TITLE
Cannot Obtain LIBOR Quotes by ID(33003)

### ISSUE THREAD

**Issue by rubikscube09** [mortada/fredapi#39]
Hello,

First of all I wanted to say this is a great package! However I seem to get an error when running `fred.search_by_category(33003)` which corresponds to getting LIBOR rates from the FRED site. In particular I get `ValueError: No series exists for category id: 33003` when the series do exist and can be found at: https://fred.stlouisfed.org/categories/33003

**Comment by Liam3851** [comment]
LIBOR is no longer free via API access due to licensing restrictions from ICE, see #33, #34, #35.

**Comment by rubikscube09** [comment]
> Thanks - closed!
