### ISSUE TITLE
'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by LazyTrader** [mortada/fredapi#41]
Hi All,

I am attempting to retrieve data in the following manner:

`from fredapi import Fred`
`fred = Fred(api_key = 'MyAPIKey')`
`data = fred.get_series('SP500')`

But doing so results in the error:

`'xml.etree.ElementTree.Element' object has no attribute 'getchildren'`

Is this due to a missing dependency and is there a workaround available?

**Comment by mortada** [comment]
sounds like the same issue as this one? https://github.com/mortada/fredapi/issues/36

**Comment by mortada** [comment]
if so, simply upgrade to the latest version of `fredapi`

**Comment by LazyTrader** [comment]
Just realised that the version I got from conda-forge is 0.4.2. Is it possible to get conda forge to upload version 0.4.3?

**Comment by mortada** [comment]
interesting, I actually only upload to pip, not sure how it got uploaded to conda-forge

https://anaconda.org/conda-forge/fredapi

**Comment by drewsaunders** [comment]
I have an Anaconda installation, as well. I installed with conda (which only gets 0.4.2), then upgraded with pip: 
> pip install --upgrade fredapi
This gets 0.4.3 from pypi. I am hoping this will minimize the chance of some conflicts. So far (which isn't very), so good!
Drew
