### ISSUE TITLE
Bad Request. This exceeds the maximum number of vintage dates allowed (2000).

### ISSUE THREAD

**Issue by Doug290** [mortada/fredapi#48]
When fetching for T5YIFR, for instance, there's an error.

OBS: using get_series_all_releases() method

**_Bad Request.  There are 2004 vintage dates in the specified real-time period: 1776-07-04 to 9999-12-31.  This exceeds the maximum number of vintage dates allowed (2000)._**

Maybe the solution would be to add a date range for this method? Or option to increase the number of vintages dates?

Thanks

**Comment by mortada** [comment]
please use version 0.5.0, thanks!

**Comment by RainmakerP** [comment]
Already using v0.5.0 yet this issue persists.

In case you want to recreate the issue, try running this command:

df = fred.get_series_all_releases("T10Y2Y")

**Comment by ohhenrylee** [comment]
Same issue for me on version 0.5.2 with T10Y2Y
