### ISSUE TITLE
How to integrate FRED API with ZOHO Api

### ISSUE THREAD

**Issue by dilshad-geol** [mortada/fredapi#53]
How to integrate FRED API with ZOHO Api

**Comment by mortada** [comment]
what's your use case? I've not heard of ZOHO

**Comment by dilshad-geol** [comment]
Actually, I want to use FRED Api within Zoho Analytics, so that I can retrieve data from Fred to my Zoho analytics, I've heard about Zoho API and FRED Api. I think it is possible to do that. Can you help?
