### ISSUE TITLE
FRED API to require HTTPS August 18.

### ISSUE THREAD

**Issue by kgtaylor** [mortada/fredapi#6]
Hello,

I work on FRED at the St. Louis Fed.  Beginning on August 18, 2015, the FRED API will require HTTPS requests.  This change will help provide secure communication with the FRED API.  An automatic redirect will forward HTTP requests to HTTPS.  We recommend that you update the URLs in your code.  The API currently supports HTTPS to allow you to test your applications with this secure protocol.

Please contact us at webmaster@research.stlouisfed.org or 314-444-FRED (3733) if you have questions or concerns.  Thanks for using FRED and the FRED API.

Sincerely,
Keith Taylor
keith.g.taylor@stls.frb.org

**Comment by elmotec** [comment]
Thanks for heads up Keith. I'll provide a patch shortly.

**Comment by mortada** [comment]
@kgtaylor thanks for the heads-up. This should be a simple change on our side and I'll make sure to do a new release before the switch. 

@elmotec could you please create a separate PR for this change? I think that'd be better, thanks!

**Comment by elmotec** [comment]
Hey @mortada. Thanks for taking a look. I'll try to split the PR but the HTTPS change are ahead of the test refactoring. I'll see what I can do.

**Comment by mortada** [comment]
I just made a new release and `fredapi` version `0.3.7`  is now using HTTPS

thanks for the PR @elmotec!
